# Generated by Django 3.2.3 on 2021-05-17 12:01

import catalogapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
                ('uid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Код')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=catalogapp.models.get_image_name_category, verbose_name='Изображение 270x301')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное наименование')),
                ('art', models.CharField(blank=True, max_length=10, null=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('characteristics', models.TextField(blank=True, max_length=2048, verbose_name='Характеристики')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Старая цена')),
                ('discount_per', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('quantity', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Остаток')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=15, null=True, verbose_name='Вес')),
                ('cpu_slug', models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url')),
                ('good_uid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Код 1C')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalogapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default=None, upload_to=catalogapp.models.get_image_name_picture, verbose_name='Изображение')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
