# Generated by Django 3.2.3 on 2021-05-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='discount_per',
        ),
        migrations.RemoveField(
            model_name='good',
            name='old_price',
        ),
    ]
