# Generated by Django 3.2.3 on 2021-06-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_auto_20210517_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Вес'),
        ),
    ]
